# Generated by Django 4.0.2 on 2022-03-21 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20210804_1131'),
        ('mainapp', '0006_auto_20210806_1510'),
    ]

    operations = [
    ]
