# Generated by Django 4.0.2 on 2022-03-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_merge_0006_auto_20210804_1131_0006_auto_20210806_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='specification',
            field=models.CharField(choices=[('FRONTEND', 'FRONTEND'), ('BACKEND', 'BACKEND'), ('ANDROID', 'ANDROID'), ('IOS', 'IOS'), ('FLUTTER', 'FLUTTER'), ('REACT-N', 'REACT-N'), ('DESKTOP', 'DESKTOP'), ('FULLSTACK', 'FULLSTACK'), ('FRONTEND', 'FRONTEND'), ('BACKEND', 'BACKEND'), ('ANDROID', 'ANDROID'), ('IOS', 'IOS'), ('FLUTTER', 'FLUTTER'), ('REACT-N', 'REACT-N'), ('DESKTOP', 'DESKTOP'), ('FULLSTACK', 'FULLSTACK')], default='FRONTEND', max_length=10),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='specification',
            field=models.CharField(choices=[('FRONTEND', 'FRONTEND'), ('BACKEND', 'BACKEND'), ('ANDROID', 'ANDROID'), ('IOS', 'IOS'), ('FLUTTER', 'FLUTTER'), ('REACT-N', 'REACT-N'), ('DESKTOP', 'DESKTOP'), ('FULLSTACK', 'FULLSTACK'), ('FRONTEND', 'FRONTEND'), ('BACKEND', 'BACKEND'), ('ANDROID', 'ANDROID'), ('IOS', 'IOS'), ('FLUTTER', 'FLUTTER'), ('REACT-N', 'REACT-N'), ('DESKTOP', 'DESKTOP'), ('FULLSTACK', 'FULLSTACK')], default='FRONTEND', max_length=10),
        ),
    ]
